#!/bin/zsh

script_name=$(basename $0)

growl() {
  message="display notification \"$*\" with title \"VideoTransport\""
  osascript -e "$message"
}

log() {
  echo "$@"
  $enable_growl && growl "$@"
  logger -p user.notice -t $script_name "$@"
}

err() {
  echo "$@"
  $enable_growl && growl "$@"
  logger -p user.error -t $script_name "$@"
}

die() {
  err "$*"
  exit 111
}

try() {
  "$@" || die "cannot $*"
}

usage() {
  echo "\n$script_name\n  usage: video_transport -u username -h hostname -r remote_path -f local_file [-g]"
}

# Main

username=
hostname=
filename=
remote_path=
enable_growl=false

while [ "$1" != "" ]; do
  case $1 in
    -u | --username )       shift
                            username=$1
                            ;;
    -h | --hostname )       shift
                            hostname=$1
                            ;;
    -r | --remote_path )    shift
                            remote_path=$1
                            ;;
    -f | --filename )       shift
                            filename=$1
                            ;;
    -g | --growl )          shift
                            enable_growl=true
                            ;;
    * )                     usage
                            exit 1
  esac
  shift
done

if [ ! -f "$filename" ]; then
  die usage
fi

mime_type=$(file --mime-type "$filename")
if ! grep -q "video/quicktime" <<< $mime_type; then
  die "$filename is not a quicktime video."
fi

try scp $filename $username@$hostname:$remote_path
log "$(basename $filename) uploaded to $hostname"
