#!/bin/zsh

readonly script_name=$(basename $0)
readonly dir_name=$(dirname $0)
readonly video_file=$1

growl() {
  message="display notification \"$*\" with title \"VideoTransport\""
  osascript -e "$message"
}

log() {
  echo "$@"
  logger -p user.notice -t $script_name "$@"
}

err() {
  echo "$@"
  logger -p user.error -t $script_name "$@"
}

die() {
  err "$*"
  exit 111
}

try() {
  "$@" || die "cannot $*"
}

upload_to_file_server() {
  mkdir $MOUNT_POINT
  try mount_afp $FILE_SERVER $MOUNT_POINT
  try cp -r $1 $MOUNT_POINT
  umount $MOUNT_POINT
  log "$1 uploaded to $FILE_SERVER_HOSTNAME"
}

if [ ! -f "$video_file" ]; then
  die "USAGE: $0 filename"
fi

mime_type=$(file --mime-type "$video_file")
if ! grep -q "video/quicktime" <<< $mime_type; then
  die "$1 is not a quicktime video."
fi

try source "$dir_name/.env"
upload_to_file_server $video_file

